var GAME_LEVELS = [
  ["                                                                                ",
   "       o                                                                        ",
   "                                                                                ",
   "                                                                                ",
   "       x                                                                        ",
   "                                                                   o            ",
   "                                                    o             xxx           ",
   "                                                   xx     xx     xx!xx          ",
   "                                                                 x!!!x          ",
   "                                 xxxxxxxxx                       xx!xx          ",
   "                    xx        s       o       g                   xvx           ",
   "               o           xxxxxxxxxxxxxxxxxxxxxx                           xx  ",
   "  xx           x                                                            ox  ",
   "  x                                                                          x  ",
   "  x                                      xxxxx                     xx   xxx  x  ",
   "  x                                                                          x  ",
   "  x  @                  o                                        xxxxx   o   x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "             x  x             x   x                  x     x                    ",
   "             x!!x             x!!!x                  x!!!!!x                    ",
   "             x!!x             x!!!x                  x!!!!!x                    ",
   "             xxxx             xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                                                                  ox!x  ",
   "                                      x!!x                        o    o                                     x!x  ",
   "                                      x!!xxxxxxxxxx             xxxxxxxxxxxx                                 x!x  ",
   "                                      xx!!!!!!!!!!xx                                                         x!x  ",
   "                                       xxxxxxxxxx!!x                                              o   o   o  x!x  ",
   "                  o                             xx!x                                                         x!x  ",
   "                  x                              x!x               o   o                      xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx               x   x                   !!!!!!!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xvxxxxxxxxxxxxxxxxxxx   ",
   "              !!!!!!!!!  xx                                   xx!!!!!!!!!!!xx                                     ",
   "              vx!!!!!xv                                        xxxx!!!!!xxxx                                      ",
   "                x!!!x               xx         x     x            xxxxxxx                    xxx                  ",
   "                 xxx                           x     x                                       x x                  ",
   "                                               x     x                                       x                    ",
   "      l                                      xxx     x      o  o                    o        x                    ",
   "                                               xx    x                              x        x                    ",
   "                                               x     x                   x!!!!!!!!!!!!       x                    ",
   "               xx   xx          x   x          x     x               x   x!!!!!!!!!!!!       x                    ",
   "              xx     xx         x o x          x     x     xxxxxx    x   x!!!xxxxxxxxx       x                    ",
   "             xx       xx        x   x          x    xx               x   x!!!x               x                    ",
   "     @       x         x       xx   x          x     x               x   x!!!x               x                    ",
   "    xxx      x         x        x o  x         x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x        x    x         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!x x!!!x    xx!!!!!!!x      x!!!!!!!!!!     x     =     x x        ox                    ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!x x!!!x  o  xxxxxxxx       x!!!!!!!xx!     xxxxxxxxxxxxx xx!!!!!!xx                     ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!x x!!!x     xxxxxxxx      xx!!!!!!xx !                    xx!!!!!xx                     ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!x x!!!x  s       o    g  xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!x x!!!x!!xxxxxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!xox!!!xxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x     o   x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxxxx       ",
   "                                                                                                  x   x       ",
   "                                                o   o                                             x  @x       ",
   "                                          xxxxxxxxxxxxxxxxxx    xx                                x  xx       ",
   "                                      g            o             x                             xxxx   x       ",
   "                                      xxxxxxxxxxxxxxxxxx         x                             x      x       ",
   "                                                       x     s   x                             x      x       ",
   "                        xxx                            x     x   x                             x      x       ",
   "                                                       x         x                             x      x       ",
   "                                 o                     x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      x       ",
   "                                 x                     x                o       o        o            x       ",
   "                   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!       x     g     xx        xx    xx        xx   s   x       ",
   "                   vx!!!!!!!!!!!!!!!!!!!!!!!!!xv       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "                     x!!!!!!!!!!!!!!!!!!!!!!!x                                                                ",
   "                      xxxxxxxxxxxvvxxxxxxxxxxx            xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                 oo                                             o                             ",
   "                         xxxxxxxxxxxxxxxxxxx                                    x      x                      ",
   "                                                                                                              ",
   "                                                 l      o                x                  x                 ",
   "                                                        xx                                                    ",
   "                                                                                                              ",
   "                xxxx                                                                                          ",
   "                                                                                          x                   ",
   "                                                        ||      x             x     x               o         ",
   "    o                                                                                               x         ",
   "    x                                                                                                         ",
   "                             o                                           o                                    ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "      x     x   xx    x    x                                                                                  ",
   "       x   x   x  x   x    x                                                                                  ",
   "        x x   x    x  x    x                                                                                  ",
   "         x   x      x x    x                                                                                  ",
   "         x    x    x  x    x                                                                                  ",
   "         x     x  x    x  x                                                                                   ",
   "         x      xx      xx                                                                                    ",
   "                                   x                                                                          ",
   "      x     x     x  x    x     x  x                                                                          ",
   "      x    x x    x  x   x x    x  x                                                                          ",
   "      x    x x    x  x  x   x   x  x                                                                          ",
   "      x    x x    x  x  x   x   x  x                                                                          ",
   "       x  x   x  x   x  x    x x                                                                              ",
   "        xx     xx    x  x     x    x                                                                          ",
   "                                                                                                              ",
   "    @                                                                                                         ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                        ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
